const myConfig = {
    "automaticRearrangeAfterDropNode": true,
    "collapsible": true,
    "directed": true,
    "focusAnimationDuration": 0.25,
    "focusZoom": 1,
    "freezeAllDragEvents": false,
    "height": 550,
    "highlightDegree": 2,
    "highlightOpacity": 0.2,
    "linkHighlightBehavior": true,
    "maxZoom": 1,
    "minZoom": 1,
    "nodeHighlightBehavior": true,
    "panAndZoom": false,
    "staticGraph": false,
    "staticGraphWithDragAndDrop": false,
    "backgroundColor": "#efefef",
    "d3": {
      "alphaTarget": 0.05,
      "gravity": -500,
      "linkLength": 140,
      "linkStrength": 2,
      "disableLinkForce": false
    },
    "node": {
      "color": "#084B83",
      "fontColor": "black",
      "fontSize": 10,
      "fontWeight": "normal",
      "highlightColor": "red",
      "highlightFontSize": 14,
      "highlightFontWeight": "bold",
      "highlightStrokeColor": "red",
      "highlightStrokeWidth": 2,
      "mouseCursor": "pointer",
      "opacity": 0.9,
      "renderLabel": true,
      "size": 600,
      "strokeColor": "none",
      "strokeWidth": 1,
      "svg": "",
      "symbolType": "circle",
      "labelPosition": "bottom"
    },
    "link": {
      "color": "lightgray",
      "fontColor": "black",
      "fontSize": 8,
      "fontWeight": "normal",
      "highlightColor": "red",
      "highlightFontSize": 8,
      "highlightFontWeight": "normal",
      "labelProperty": "label",
      "mouseCursor": "pointer",
      "opacity": 1,
      "renderLabel": false,
      "semanticStrokeWidth": true,
      "strokeWidth": 2,
      "markerHeight": 6,
      "markerWidth": 6,
      "strokeDasharray": 0,
      "strokeDashoffset": 0,
      "strokeLinecap": "butt"
    }
  }

  export default myConfig